server:
  port: 8095
jwt:
  secret-key: "370c7005cac2e7495f3ee8b6edfe98594e292da208fb21b5d58e63fe064624b3"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/persons
    username: root
    password: P@ssword123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
